// Gated LIVE conformance suite — the TS analogue of Go's
// pkg/harness/conformance_test.go. It runs against the REAL installed harness
// binaries and is therefore OPT-IN: skipped by default so CI without the
// binaries stays green. Enable it with:
//
//   CONFORMANCE=1 npx vitest run test/conformance.test.ts
//
// GATE NAME. This file gates on CONFORMANCE=1 while its sibling live suites
// (test/drift/conformance.test.ts, the env suites) gate on
// META_HARNESS_CONFORMANCE=1. The split is KNOWN and DELIBERATE, not an
// oversight: test/conformance/README.md is GENERATED by
// scripts/sync-conformance.sh, which bakes the gate name in, so unifying the two
// is a vendoring-script change and is out of scope here.
//
// SIDE EFFECT ON ~/.claude.json. This suite launches the REAL claude binary in a
// mkdtempSync working dir against the developer's REAL $HOME, and claude records
// a `projects` entry for each working dir it is launched in, plus
// `hasTrustDialogAccepted`. Half 2 passes AutoAcceptTrust precisely so that
// dialog is answered — i.e. persisted. That accretion is inherent, not a bug:
// HOME isolation is not viable because a fresh HOME lands both CLIs on the
// onboarding wall, where no conformance fact is observable.
//
// It has two independent halves, one per conformance fact:
//
//   1. VERSION-DRIFT. For each adapter declared in versions.json, detect the
//      installed binary and its version (src/discovery), then assert that the
//      detected version matches the pinned/verified fact (versions.ts Entry).
//      This is PRECISELY planAcquisition's fact 3 (capability-by-version) — the
//      third of the three facts its Stream gate depends on. When the installed
//      version diverges from the pin the test FAILS with a clear drift report
//      rather than silently passing, so the version predicate cannot drift out
//      from under the acquisition plan unnoticed.
//
//   2. SENTINEL ROUND-TRIP. For each installed adapter, drive the REACHABLE
//      acquisition path end-to-end through the acquisition-attached chat seam
//      (Open + onAcquisitionEvent + StreamTap) with a sentinel prompt. Because
//      all four current adapters resolve to Hooks/Off (no adapter marks itself
//      StreamInterleaved, and Hooks delivery is not viable in A1), the LATCHED
//      mode is never Stream — the round-trip exercises the Hooks/Off path and
//      asserts the acquisition subsystem behaves correctly for that mode:
//        - the harness session id is captured exactly once (no double-write),
//        - the latched mode is Hooks or Off — never Stream — for real adapters,
//        - every delivered acquisition event obeys admitParent for that mode.
//      Live Stream against real binaries is intentionally NOT exercised here;
//      Stream's only A1 exercise is the fake-adapter test in stream_acquisition.
//
// Alongside the two halves it carries the FLAG-SURFACE CHECKS (checks 1-2 of
// META-HARNESS-131, deliberately numbered so they do not collide with the
// "halves" above). Every anchor the security-mode feature stands on is a CLI
// flag on a fast-moving binary, and those flags have already moved under us:
// codex REMOVED --full-auto (it now hard-errors) and claude flipped its DEFAULT
// permission mode. An unknown flag makes the harness exit only when a caller
// actually launches with that mode, in production, with no attribution back to
// the rename; these checks convert that future launch failure into a named drift
// report. Unit tests over the recorded corpus cannot do this — the fixtures are
// frozen bytes and keep passing forever after the real CLI has moved on.
//
// The checks read `<binary> --help` INSIDE the test bodies, never at module
// scope: with CONFORMANCE unset this file must spawn no --help subprocess.
//
// Every half and every check is cleanly SKIPPED (not failed) when CONFORMANCE is
// unset or the binary is absent.

import { describe, expect, test } from "vitest";
import { spawnSync } from "node:child_process";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { Context } from "../src/internal/async/index.ts";
import {
  EventTurn,
  Open,
  RoleAssistant,
  TurnStateComplete,
  TurnStateErrored,
  newMemStore,
  resolveAdapter,
  type Conversation,
  type Turn,
} from "../src/chat/index.ts";
import { AutoAcceptTrust } from "../src/oneshot/index.ts";
import { lookup, type Info } from "../src/discovery/index.ts";
import { all as allVersions } from "../src/versions/index.ts";
import {
  AcquisitionModeHooks,
  AcquisitionModeOff,
  AcquisitionModeStream,
  describeAcquisitionMode,
  type AcquisitionMode,
} from "../src/turns/index.ts";
import { SourceLive, type EventEnvelope } from "../src/transcript/index.ts";
import {
  planAcquisition,
  resolveProfile,
} from "../src/acquisition/internal/planAcquisition.ts";
import { admitParent } from "../src/acquisition/internal/filter.ts";
import {
  ClaudeModeAcceptEdits,
  ClaudeModeBypassPermissions,
  ClaudeModeDontAsk,
  ClaudePermissionModeFlag,
  ClaudeSkipPermissionsFlags,
  CodexApprovalFlags,
  CodexApprovalNever,
  CodexApprovalOnRequest,
  CodexApprovalUntrusted,
  CodexBypassFlag,
  CodexProfileFlags,
  CodexSandboxDangerFullAccess,
  CodexSandboxFlags,
  CodexSandboxReadOnly,
  CodexSandboxWorkspaceWrite,
  PermissionModeAuto,
  PermissionModeManual,
  PermissionModePlan,
} from "../src/wrapper/internal/permissionrungs.ts";
import { isSupportedPermissionMode } from "../src/wrapper/internal/permission.ts";

// ── Gate ────────────────────────────────────────────────────────────────────

const CONFORMANCE = process.env.CONFORMANCE === "1";

// The canonical harnesses whose adapters resolveAdapter knows about, in a stable
// order. Every entry in versions.json is one of these.
const HARNESSES = ["codex", "claude-code", "opencode", "pi"] as const;

// Detect each installed binary ONCE at load time. discovery.lookup runs the
// registered version probe, so `info.detectedVersion` is the live fact.
const infos: Record<string, Info> = {};
for (const name of HARNESSES) {
  infos[name] = lookup(name);
}

// ── Sentinel prompt ───────────────────────────────────────────────────────────

// A prompt whose reply is trivially checkable and cannot be confused with the
// echoed prompt itself.
const PROMPT = "Reply with exactly the single word: pomegranate";

const TEST_TIMEOUT = 240_000;
const CTX_DEADLINE = TEST_TIMEOUT - 15_000;

/** Drains conversation events until the assistant turn reaches a terminal state. */
async function waitTerminal(ctx: Context, conv: Conversation): Promise<Turn> {
  const bus = conv.events();
  for (;;) {
    const outcome = await Promise.race([
      bus.receive(),
      ctx.done().then(() => "cancel" as const),
    ]);
    if (outcome === "cancel")
      throw ctx.err() ?? new Error("conformance: context done");
    const { value, ok } = outcome;
    if (!ok)
      throw new Error(
        "conformance: event channel closed before a terminal turn",
      );
    const ev = value!;
    if (
      ev.type === EventTurn &&
      ev.turn?.role === RoleAssistant &&
      (ev.turn.state === TurnStateComplete ||
        ev.turn.state === TurnStateErrored)
    ) {
      return ev.turn;
    }
  }
}

/**
 * expectedLatchedMode mirrors conversation.ts's acquisition plan for a run:
 * resolveProfile over the DETECTED discovery info + the real adapter, then
 * planAcquisition with a sink present and Hooks delivery not viable (the A1
 * facts). This is the mode the live seam will latch — computed here so the
 * round-trip can assert it is never Stream for a real adapter.
 */
function expectedLatchedMode(info: Info): AcquisitionMode {
  const adapter = resolveAdapter(info.harness);
  const profile = resolveProfile({
    info: {
      harness: info.harness,
      installed: true,
      detectedVersion: info.detectedVersion,
      pinnedVersion: info.pinnedVersion,
    },
    adapter,
  });
  return planAcquisition(AcquisitionModeStream, {
    profile,
    haveSink: true,
    // Hooks side-channel delivery is not viable in A1 (mirrors conversation.ts).
    hooksViable: false,
  });
}

// ── Half 1: version-drift ─────────────────────────────────────────────────────

describe("conformance: version-drift (CONFORMANCE=1)", () => {
  for (const name of HARNESSES) {
    const info = infos[name];
    const entry = allVersions().get(name);
    const pinned = entry?.pinned ?? "";

    // Skip when the suite is not opted-in OR the binary is not installed OR the
    // harness carries no pin to drift against (an unpinned harness like opencode
    // has no version fact to enforce). None of these are failures.
    const skip = !CONFORMANCE || !info.installed || pinned === "";

    test.skipIf(skip)(
      `${name}: installed version matches pinned/verified fact`,
      () => {
        // A probe that ran but failed is a hard error: we cannot assert the
        // version fact, and a silent pass would defeat the guard.
        expect(
          info.versionProbeError,
          `${name}: version probe failed: ${info.versionProbeError}`,
        ).toBe("");
        expect(
          info.detectedVersion,
          `${name}: no version detected from the installed binary`,
        ).not.toBe("");

        // The load-bearing assertion: the installed binary's version equals the
        // pinned/verified version. A divergence means the capability-by-version
        // fact planAcquisition's Stream gate relies on has DRIFTED — surface it
        // loudly (fail) instead of passing silently.
        expect(
          info.detectedVersion,
          `${name}: VERSION DRIFT — installed ${info.detectedVersion} != pinned ${pinned} ` +
            `(verified ${entry?.verifiedAt || "?"}). Re-verify the adapter against the ` +
            `installed upstream and update versions.json, or reinstall the pinned version.`,
        ).toBe(pinned);
        // discovery's own drift flag must agree with the raw comparison.
        expect(info.versionMatchesPin).toBe(true);
      },
    );
  }
});

// ── Half 2: sentinel round-trip ────────────────────────────────────────────────

describe("conformance: sentinel round-trip (CONFORMANCE=1)", () => {
  for (const name of HARNESSES) {
    const info = infos[name];
    const skip = !CONFORMANCE || !info.installed;

    test.skipIf(skip)(
      `${name}: reachable acquisition path — id captured once, latched mode is Hooks/Off, admitParent honored`,
      async () => {
        // Real adapters never satisfy the Stream gate (none are interleaved),
        // and Hooks delivery is not viable in A1 — so the latched mode is Off (or
        // Hooks if a future adapter makes it viable), NEVER Stream. Assert that
        // BEFORE launching, so a drift in the gate predicates is caught even if
        // the live launch is flaky.
        const latched = expectedLatchedMode(info);
        expect(
          latched,
          `${name}: latched acquisition mode is ${describeAcquisitionMode(latched)}, ` +
            `expected a reachable mode (hooks/off) — Stream must be unreachable for real adapters`,
        ).not.toBe(AcquisitionModeStream);
        expect([AcquisitionModeHooks, AcquisitionModeOff]).toContain(latched);

        const dir = mkdtempSync(join(tmpdir(), `conformance-${name}-`));
        const store = newMemStore();
        const events: EventEnvelope[] = [];
        const { ctx, cancel } = Context.withDeadline(
          Context.background(),
          CTX_DEADLINE,
        );

        let conv: Conversation | undefined;
        try {
          conv = await Open(ctx, {
            harness: info.harness,
            binaryPath: info.path,
            workingDir: dir,
            store,
            inputPolicy: AutoAcceptTrust,
            // Attach the acquisition subsystem: a sink makes the plan pick the
            // reachable mode and routes any admitted events here.
            acquisitionMode: AcquisitionModeStream,
            onAcquisitionEvent: (env) => events.push(env),
          });

          // Drive the sentinel prompt through the same control/send seam chat
          // exposes to callers.
          const release = await conv.acquireControl(ctx);
          try {
            await conv.send(ctx, PROMPT);
          } finally {
            release();
          }

          const turn = await waitTerminal(ctx, conv);
          expect(
            turn.state,
            `${name}: turn errored: ${turn.reason ?? ""}`,
          ).toBe(TurnStateComplete);
          expect(turn.text.trim(), `${name}: empty assistant reply`).not.toBe(
            "",
          );

          // Session id captured EXACTLY once: the store record carries a stable,
          // non-empty harness session id, and a second read is byte-identical —
          // no double-write from the acquisition tap (StreamTap only READS it).
          const first = await store.getSession(conv.sessionID());
          expect(
            first.harnessSessionID,
            `${name}: harness session id was not captured`,
          ).not.toBe("");
          const second = await store.getSession(conv.sessionID());
          expect(second.harnessSessionID).toBe(first.harnessSessionID);
          // The live conversation view agrees with the persisted record.
          expect(conv.session.harnessSessionID).toBe(first.harnessSessionID);

          // Every delivered acquisition event must have been admissible under the
          // central authority filter for the LATCHED mode. For Off no event is
          // ever admitted (StreamTap goes inert), so this also asserts the sink
          // stayed silent; for Hooks it asserts the source/kind authority held.
          for (const env of events) {
            const source = (env.event.source ?? SourceLive) as "live" | "file";
            const isSubagent = (env.parentSessionID ?? "") !== "";
            expect(
              admitParent(latched, source, env.event.type ?? "", isSubagent),
              `${name}: event kind=${env.event.type} source=${source} was delivered but ` +
                `admitParent(${describeAcquisitionMode(latched)}) rejects it`,
            ).toBe(true);
            // Delivered events carry the run identity and the captured id.
            expect(env.runID).toBe(conv.sessionID());
            expect(env.harness).toBe(info.harness);
          }
          // In the Off latched mode the acquisition sink must stay silent — the
          // filter admits nothing, so no double-record leaks through.
          if (latched === AcquisitionModeOff) {
            expect(
              events.length,
              `${name}: Off mode delivered ${events.length} acquisition events; expected none`,
            ).toBe(0);
          }

          await conv.quit(ctx).catch(() => {});
        } finally {
          cancel();
          if (conv) {
            const { ctx: closeCtx } = Context.withDeadline(
              Context.background(),
              3000,
            );
            await conv.close(closeCtx).catch(() => {});
          }
          rmSync(dir, { recursive: true, force: true });
        }
      },
      TEST_TIMEOUT,
    );
  }
});

// ── Checks 1-2: harness permission-flag surface ───────────────────────────────
//
// Assert the REAL binaries still offer the flags and values the shipped
// permission code emits. Only claude-code and codex are covered: opencode and pi
// have no launch-time permission axis at all (effectiveLaunchRung's `default:`
// arm returns ""), so there is nothing to drift.
//
// DERIVE, DON'T RETYPE. Both the flag NAMES and the flag VALUES below come from
// the exported constants in src/wrapper/internal/permissionrungs.ts — the replay
// authority for these spellings, and therefore their natural home. A value
// retyped into this file would drift against the shipped map instead of against
// the CLI, which is the opposite of what this check is for.

/** How long a `--help` invocation may take before we call it hung. */
const HELP_TIMEOUT = 30_000;

/**
 * helpText runs `<binary> --help` and returns stdout+stderr.
 *
 * It takes the discovery Info, NOT a bare binary name: `info.path` is the
 * override-aware absolute path (HARNESS_BINARY_* / HARNESS_BINARY), so this
 * probes exactly the binary the other halves launch. A bare `claude` would
 * silently probe a different one.
 *
 * Called only from inside a test body, so the default (CONFORMANCE unset) run
 * spawns nothing.
 */
function helpText(info: Info): string {
  const res = spawnSync(info.path, ["--help"], {
    encoding: "utf8",
    timeout: HELP_TIMEOUT,
    maxBuffer: 32 * 1024 * 1024,
  });
  if (res.error) {
    throw new Error(
      `${info.harness}: could not run \`${info.path} --help\`: ${res.error.message}`,
    );
  }
  return `${res.stdout ?? ""}\n${res.stderr ?? ""}`;
}

/**
 * squash collapses every run of whitespace to a single space. Both CLIs
 * hard-wrap their choice lists at the detected terminal width, so a literal
 * match against the unwrapped rendering fails for reasons that have nothing to
 * do with drift.
 */
function squash(text: string): string {
  return text.replace(/\s+/g, " ");
}

/**
 * flagSection returns the slice of squashed --help starting at `flag`, so a
 * value is asserted against the flag's OWN entry rather than anywhere in the
 * help text (codex's `never` and `read-only` both occur in unrelated prose).
 * Returns "" when the flag is absent — the caller asserts presence first.
 */
function flagSection(help: string, flag: string, span = 800): string {
  const at = help.indexOf(flag);
  if (at < 0) return "";
  return help.slice(at, at + span);
}

/** A short, quotable excerpt of the flag's help entry for a drift report. */
function excerpt(help: string, flag: string): string {
  const section = flagSection(help, flag, 320);
  return section === "" ? "(flag absent from --help)" : section.trim();
}

const SYMBOLS = "src/wrapper/internal/permissionrungs.ts";

describe("conformance: permission-flag surface (CONFORMANCE=1)", () => {
  // ── Check 1: claude --help still offers --permission-mode + its values ─────

  {
    const info = infos["claude-code"];
    const skip = !CONFORMANCE || !info.installed;

    test.skipIf(skip)(
      `claude-code: --help offers ${ClaudePermissionModeFlag} with every mapped value, plus the bypass flags`,
      () => {
        const help = squash(helpText(info));
        const version = info.detectedVersion || "?";

        // The values claude must still accept. TWO classes, both load-bearing:
        //
        //  - EMITTABLE — what argsWithHarnessPermissionMode actually puts on
        //    argv: "plan", "manual", "acceptEdits" (the ask rung), "auto",
        //    "bypassPermissions" (the bypass rung);
        //  - RECOGNIZED-BUT-NOT-EMITTED — "dontAsk". We never emit it, but a
        //    caller may pass it and isSupportedPermissionMode accepts it. It is
        //    OFF the canonical ladder: claudeRung returns "" for it and it has
        //    no footer, so it is a spelling we recognize, not a rung.
        //
        // Derived as: the three exported claude-native spellings ∪ the canonical
        // rungs claude spells identically. NOT permissionRungs(), which returns
        // the canonical vocabulary — claude accepts neither "ask" nor "bypass".
        const derived = [
          ClaudeModeAcceptEdits,
          ClaudeModeDontAsk,
          ClaudeModeBypassPermissions,
          PermissionModePlan,
          PermissionModeManual,
          PermissionModeAuto,
        ];
        // Cross-check against the shipped input predicate (META-HARNESS-100):
        // every derived spelling must still be an accepted input, or the two
        // halves of the shipped map have already diverged from each other.
        const expected = derived.filter((v) =>
          isSupportedPermissionMode("claude-code", v),
        );
        expect(
          expected,
          `claude-code: isSupportedPermissionMode rejects ${derived
            .filter((v) => !isSupportedPermissionMode("claude-code", v))
            .join(", ")} — the derived --help expectation and the shipped ` +
            `permission map (src/wrapper/internal/permission.ts) disagree`,
        ).toEqual(derived);

        expect(
          help.includes(ClaudePermissionModeFlag),
          `claude ${version} no longer offers \`${ClaudePermissionModeFlag}\` ` +
            `(expected from ClaudePermissionModeFlag, ${SYMBOLS}); \`--help\` no longer ` +
            `mentions it at all. The whole claude permission axis has been renamed — ` +
            `update claudePermissionValue/claudeGuardFlags in ` +
            `src/wrapper/internal/permission.ts and effectiveLaunchRung in ${SYMBOLS}.`,
        ).toBe(true);

        const section = flagSection(help, ClaudePermissionModeFlag);
        for (const value of expected) {
          // The choice list is rendered with quotes: (choices: "acceptEdits", …).
          expect(
            section.includes(`"${value}"`),
            `claude ${version} no longer accepts \`${ClaudePermissionModeFlag} ${value}\` ` +
              `(expected from ${SYMBOLS}); \`--help\` now shows: ` +
              `${excerpt(help, ClaudePermissionModeFlag)} . Update the claude arm of ` +
              `claudePermissionValue/argsWithHarnessPermissionMode in ` +
              `src/wrapper/internal/permission.ts and claudeRung in ${SYMBOLS}.`,
          ).toBe(true);
        }

        // The blanket bypass flags the SHIPPED code path already injects:
        // metaHarnessArgs (src/cli/structured-runner.ts) adds
        // --dangerously-skip-permissions under --sandbox-defaults today.
        for (const flag of ClaudeSkipPermissionsFlags) {
          expect(
            help.includes(flag),
            `claude ${version} no longer offers \`${flag}\` (expected from ` +
              `ClaudeSkipPermissionsFlags, ${SYMBOLS}); \`--help\` no longer mentions it. ` +
              `Launching with it now hard-errors — update ClaudeSkipPermissionsFlags, ` +
              `claudeGuardFlags (src/wrapper/internal/permission.ts) and metaHarnessArgs ` +
              `(src/cli/structured-runner.ts).`,
          ).toBe(true);
        }
      },
      HELP_TIMEOUT + 10_000,
    );
  }

  // ── Check 2: codex --help still offers -s/-a with their emitted values ─────

  {
    const info = infos["codex"];
    const skip = !CONFORMANCE || !info.installed;

    test.skipIf(skip)(
      "codex: --help offers -s/--sandbox, -a/--ask-for-approval, -p/--profile and the bypass flag with every emitted value",
      () => {
        const help = squash(helpText(info));
        const version = info.detectedVersion || "?";

        // clap renders a short/long pair as `-s, --sandbox`; deriving the
        // rendering from the exported flag arrays keeps both spellings asserted
        // without matching a bare `-s` (which occurs all over the help text).
        const sandboxFlag = CodexSandboxFlags.join(", ");
        const approvalFlag = CodexApprovalFlags.join(", ");
        const profileFlag = CodexProfileFlags.join(", ");

        // The two axes do NOT share a help shape at 0.144.5: -s renders a
        // one-line `[possible values: …]`, while -a renders a bulleted prose
        // list ("- on-request: The model decides …"). A `[possible values:`
        // matcher applied to -a fails, so assert PER VALUE against the flag's
        // own squashed section instead of against a joined list literal.
        const axes: {
          flag: string;
          short: string;
          symbol: string;
          values: { value: string; symbol: string }[];
        }[] = [
          {
            flag: sandboxFlag,
            short: CodexSandboxFlags[0],
            symbol: "CodexSandboxFlags",
            values: [
              { value: CodexSandboxReadOnly, symbol: "CodexSandboxReadOnly" },
              {
                value: CodexSandboxWorkspaceWrite,
                symbol: "CodexSandboxWorkspaceWrite",
              },
              {
                value: CodexSandboxDangerFullAccess,
                symbol: "CodexSandboxDangerFullAccess",
              },
            ],
          },
          {
            flag: approvalFlag,
            short: CodexApprovalFlags[0],
            symbol: "CodexApprovalFlags",
            values: [
              {
                value: CodexApprovalUntrusted,
                symbol: "CodexApprovalUntrusted",
              },
              {
                value: CodexApprovalOnRequest,
                symbol: "CodexApprovalOnRequest",
              },
              { value: CodexApprovalNever, symbol: "CodexApprovalNever" },
            ],
          },
        ];

        for (const axis of axes) {
          expect(
            help.includes(axis.flag),
            `codex ${version} no longer offers \`${axis.flag}\` (expected from ` +
              `${axis.symbol}, ${SYMBOLS}); \`--help\` no longer renders that pair. ` +
              `Update codexPermissionArgs/codexGuardFlags ` +
              `(src/wrapper/internal/permission.ts) and codexLaunchRung in ${SYMBOLS}.`,
          ).toBe(true);

          const section = flagSection(help, axis.flag);
          for (const { value, symbol } of axis.values) {
            expect(
              section.includes(value),
              `codex ${version} no longer accepts \`${axis.short} ${value}\` ` +
                `(expected from ${symbol}, ${SYMBOLS}); \`--help\` now shows: ` +
                `${excerpt(help, axis.flag)} . Update the forward map in ${SYMBOLS} ` +
                `and argsWithHarnessPermissionMode in src/wrapper/internal/permission.ts.`,
            ).toBe(true);
          }
        }

        // The blanket bypass flag effectiveLaunchRung resolves to `bypass`.
        expect(
          help.includes(CodexBypassFlag),
          `codex ${version} no longer offers \`${CodexBypassFlag}\` (expected from ` +
            `CodexBypassFlag, ${SYMBOLS}); \`--help\` no longer mentions it. Update ` +
            `CodexBypassFlag and codexGuardFlags (src/wrapper/internal/permission.ts).`,
        ).toBe(true);

        // -p/--profile is guarded but never emitted: its PRESENCE is what makes
        // effectiveLaunchRung report "" (unknowable posture), because a profile
        // fills in whichever axis the caller left unset. If codex drops it, the
        // guard becomes dead weight; if codex reuses `-p` for something else the
        // guard becomes actively wrong — either way we must hear about it.
        expect(
          help.includes(profileFlag),
          `codex ${version} no longer offers \`${profileFlag}\` (expected from ` +
            `CodexProfileFlags, ${SYMBOLS}); \`--help\` no longer renders that pair. ` +
            `The unknowable-posture guard in codexLaunchRung (${SYMBOLS}) and ` +
            `codexGuardFlags (src/wrapper/internal/permission.ts) must be re-derived — ` +
            `note claude's -p is --print, so the two harnesses must stay asymmetric.`,
        ).toBe(true);
      },
      HELP_TIMEOUT + 10_000,
    );
  }
});
