// Gated LIVE conformance suite — the TS analogue of Go's
// pkg/harness/conformance_test.go. It runs against the REAL installed harness
// binaries and is therefore OPT-IN: skipped by default so CI without the
// binaries stays green. Enable it with:
//
//   CONFORMANCE=1 npx vitest run test/conformance.test.ts
//
// GATE NAME. This file gates on CONFORMANCE=1 while its sibling live suites
// (test/drift/conformance.test.ts, the env suites) gate on
// META_HARNESS_CONFORMANCE=1. The split is KNOWN and DELIBERATE, not an
// oversight: test/conformance/README.md is GENERATED by
// scripts/sync-conformance.sh, which bakes the gate name in, so unifying the two
// is a vendoring-script change and is out of scope here.
//
// SIDE EFFECT ON ~/.claude.json. This suite launches the REAL claude binary in a
// mkdtempSync working dir against the developer's REAL $HOME, and claude records
// a `projects` entry for each working dir it is launched in, plus
// `hasTrustDialogAccepted`. Half 2 passes AutoAcceptTrust precisely so that
// dialog is answered — i.e. persisted. That accretion is inherent, not a bug:
// HOME isolation is not viable because a fresh HOME lands both CLIs on the
// onboarding wall, where no conformance fact is observable. codex accretes the
// same way into ~/.codex/config.toml: half 2 launches it against the real
// CODEX_HOME, so each run appends a `[projects."<tmp dir>"] trust_level` entry.
// CHECK 4 below is the exception — it isolates CODEX_HOME precisely so the
// posture it reads comes from its launch flags and not from the developer's
// config, and so it writes nothing there at all.
//
// It has two independent halves, one per conformance fact:
//
//   1. VERSION-DRIFT. For each adapter declared in versions.json, detect the
//      installed binary and its version (src/discovery), then assert that the
//      detected version matches the pinned/verified fact (versions.ts Entry).
//      This is PRECISELY planAcquisition's fact 3 (capability-by-version) — the
//      third of the three facts its Stream gate depends on. When the installed
//      version diverges from the pin the test FAILS with a clear drift report
//      rather than silently passing, so the version predicate cannot drift out
//      from under the acquisition plan unnoticed.
//
//   2. SENTINEL ROUND-TRIP. For each installed adapter, drive the REACHABLE
//      acquisition path end-to-end through the acquisition-attached chat seam
//      (Open + onAcquisitionEvent + StreamTap) with a sentinel prompt. Because
//      all four current adapters resolve to Hooks/Off (no adapter marks itself
//      StreamInterleaved, and Hooks delivery is not viable in A1), the LATCHED
//      mode is never Stream — the round-trip exercises the Hooks/Off path and
//      asserts the acquisition subsystem behaves correctly for that mode:
//        - the harness session id is captured exactly once (no double-write),
//        - the latched mode is Hooks or Off — never Stream — for real adapters,
//        - every delivered acquisition event obeys admitParent for that mode.
//      Live Stream against real binaries is intentionally NOT exercised here;
//      Stream's only A1 exercise is the fake-adapter test in stream_acquisition.
//
// Alongside the two halves it carries the FLAG-SURFACE CHECKS (checks 1-2 of
// META-HARNESS-131, deliberately numbered so they do not collide with the
// "halves" above). Every anchor the security-mode feature stands on is a CLI
// flag on a fast-moving binary, and those flags have already moved under us:
// codex REMOVED --full-auto (it now hard-errors) and claude flipped its DEFAULT
// permission mode. An unknown flag makes the harness exit only when a caller
// actually launches with that mode, in production, with no attribution back to
// the rename; these checks convert that future launch failure into a named drift
// report. Unit tests over the recorded corpus cannot do this — the fixtures are
// frozen bytes and keep passing forever after the real CLI has moved on.
//
// The checks read `<binary> --help` INSIDE the test bodies, never at module
// scope: with CONFORMANCE unset this file must spawn no --help subprocess.
//
// CHECK 4 (also META-HARNESS-131) closes the other end of that same wire: it
// LAUNCHES codex with the permission flags checks 1-2 merely found in `--help`,
// and asserts the live `/status` box reads the posture back through the SHIPPED
// parser. `--help` can keep a flag long after the row reporting it is renamed,
// and vice versa. It is launch-and-scrape only — no prompt is sent and the
// `/permissions` dialog is never driven (selecting a preset there writes
// ~/.codex/config.toml globally).
//
// Every half and every check is cleanly SKIPPED (not failed) when CONFORMANCE is
// unset or the binary is absent.

import { describe, expect, test } from "vitest";
import { spawnSync } from "node:child_process";
import { copyFileSync, existsSync, mkdtempSync, rmSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import { join } from "node:path";

import { Context } from "../src/internal/async/index.ts";
import {
  EventTurn,
  Open,
  RoleAssistant,
  TurnStateComplete,
  TurnStateErrored,
  newMemStore,
  normalizePermissionRung,
  parsePermissionMode,
  readyForInput,
  resolveAdapter,
  type Conversation,
  type PermissionRung,
  type Turn,
} from "../src/chat/index.ts";
import { AutoAcceptTrust } from "../src/oneshot/index.ts";
import { lookup, type Info } from "../src/discovery/index.ts";
import { all as allVersions } from "../src/versions/index.ts";
import {
  AcquisitionModeHooks,
  AcquisitionModeOff,
  AcquisitionModeStream,
  describeAcquisitionMode,
  type AcquisitionMode,
} from "../src/turns/index.ts";
import { SourceLive, type EventEnvelope } from "../src/transcript/index.ts";
import {
  planAcquisition,
  resolveProfile,
} from "../src/acquisition/internal/planAcquisition.ts";
import { admitParent } from "../src/acquisition/internal/filter.ts";
import {
  ClaudeModeAcceptEdits,
  ClaudeModeBypassPermissions,
  ClaudeModeDontAsk,
  ClaudePermissionModeFlag,
  ClaudeSkipPermissionsFlags,
  CodexApprovalFlags,
  CodexApprovalNever,
  CodexApprovalOnRequest,
  CodexApprovalUntrusted,
  CodexBypassFlag,
  CodexProfileFlags,
  CodexSandboxDangerFullAccess,
  CodexSandboxFlags,
  CodexSandboxReadOnly,
  CodexSandboxWorkspaceWrite,
  PermissionModeAuto,
  PermissionModeManual,
  PermissionModePlan,
} from "../src/wrapper/internal/permissionrungs.ts";
import { isSupportedPermissionMode } from "../src/wrapper/internal/permission.ts";
import {
  StatusBinaryNotFound,
  StatusFailed,
  StatusInterrupted,
} from "../src/wrapper/internal/status.ts";

// ── Gate ────────────────────────────────────────────────────────────────────

const CONFORMANCE = process.env.CONFORMANCE === "1";

// The canonical harnesses whose adapters resolveAdapter knows about, in a stable
// order. Every entry in versions.json is one of these.
const HARNESSES = ["codex", "claude-code", "opencode", "pi"] as const;

// Detect each installed binary ONCE at load time. discovery.lookup runs the
// registered version probe, so `info.detectedVersion` is the live fact.
const infos: Record<string, Info> = {};
for (const name of HARNESSES) {
  infos[name] = lookup(name);
}

// ── Sentinel prompt ───────────────────────────────────────────────────────────

// A prompt whose reply is trivially checkable and cannot be confused with the
// echoed prompt itself.
const PROMPT = "Reply with exactly the single word: pomegranate";

const TEST_TIMEOUT = 240_000;
const CTX_DEADLINE = TEST_TIMEOUT - 15_000;

/** Drains conversation events until the assistant turn reaches a terminal state. */
async function waitTerminal(ctx: Context, conv: Conversation): Promise<Turn> {
  const bus = conv.events();
  for (;;) {
    const outcome = await Promise.race([
      bus.receive(),
      ctx.done().then(() => "cancel" as const),
    ]);
    if (outcome === "cancel")
      throw ctx.err() ?? new Error("conformance: context done");
    const { value, ok } = outcome;
    if (!ok)
      throw new Error(
        "conformance: event channel closed before a terminal turn",
      );
    const ev = value!;
    if (
      ev.type === EventTurn &&
      ev.turn?.role === RoleAssistant &&
      (ev.turn.state === TurnStateComplete ||
        ev.turn.state === TurnStateErrored)
    ) {
      return ev.turn;
    }
  }
}

/**
 * expectedLatchedMode mirrors conversation.ts's acquisition plan for a run:
 * resolveProfile over the DETECTED discovery info + the real adapter, then
 * planAcquisition with a sink present and Hooks delivery not viable (the A1
 * facts). This is the mode the live seam will latch — computed here so the
 * round-trip can assert it is never Stream for a real adapter.
 */
function expectedLatchedMode(info: Info): AcquisitionMode {
  const adapter = resolveAdapter(info.harness);
  const profile = resolveProfile({
    info: {
      harness: info.harness,
      installed: true,
      detectedVersion: info.detectedVersion,
      pinnedVersion: info.pinnedVersion,
    },
    adapter,
  });
  return planAcquisition(AcquisitionModeStream, {
    profile,
    haveSink: true,
    // Hooks side-channel delivery is not viable in A1 (mirrors conversation.ts).
    hooksViable: false,
  });
}

// ── Half 1: version-drift ─────────────────────────────────────────────────────

describe("conformance: version-drift (CONFORMANCE=1)", () => {
  for (const name of HARNESSES) {
    const info = infos[name];
    const entry = allVersions().get(name);
    const pinned = entry?.pinned ?? "";

    // Skip when the suite is not opted-in OR the binary is not installed OR the
    // harness carries no pin to drift against (an unpinned harness like opencode
    // has no version fact to enforce). None of these are failures.
    const skip = !CONFORMANCE || !info.installed || pinned === "";

    test.skipIf(skip)(
      `${name}: installed version matches pinned/verified fact`,
      () => {
        // A probe that ran but failed is a hard error: we cannot assert the
        // version fact, and a silent pass would defeat the guard.
        expect(
          info.versionProbeError,
          `${name}: version probe failed: ${info.versionProbeError}`,
        ).toBe("");
        expect(
          info.detectedVersion,
          `${name}: no version detected from the installed binary`,
        ).not.toBe("");

        // The load-bearing assertion: the installed binary's version equals the
        // pinned/verified version. A divergence means the capability-by-version
        // fact planAcquisition's Stream gate relies on has DRIFTED — surface it
        // loudly (fail) instead of passing silently.
        expect(
          info.detectedVersion,
          `${name}: VERSION DRIFT — installed ${info.detectedVersion} != pinned ${pinned} ` +
            `(verified ${entry?.verifiedAt || "?"}). Re-verify the adapter against the ` +
            `installed upstream and update versions.json, or reinstall the pinned version.`,
        ).toBe(pinned);
        // discovery's own drift flag must agree with the raw comparison.
        expect(info.versionMatchesPin).toBe(true);
      },
    );
  }
});

// ── Half 2: sentinel round-trip ────────────────────────────────────────────────

describe("conformance: sentinel round-trip (CONFORMANCE=1)", () => {
  for (const name of HARNESSES) {
    const info = infos[name];
    const skip = !CONFORMANCE || !info.installed;

    test.skipIf(skip)(
      `${name}: reachable acquisition path — id captured once, latched mode is Hooks/Off, admitParent honored`,
      async () => {
        // Real adapters never satisfy the Stream gate (none are interleaved),
        // and Hooks delivery is not viable in A1 — so the latched mode is Off (or
        // Hooks if a future adapter makes it viable), NEVER Stream. Assert that
        // BEFORE launching, so a drift in the gate predicates is caught even if
        // the live launch is flaky.
        const latched = expectedLatchedMode(info);
        expect(
          latched,
          `${name}: latched acquisition mode is ${describeAcquisitionMode(latched)}, ` +
            `expected a reachable mode (hooks/off) — Stream must be unreachable for real adapters`,
        ).not.toBe(AcquisitionModeStream);
        expect([AcquisitionModeHooks, AcquisitionModeOff]).toContain(latched);

        const dir = mkdtempSync(join(tmpdir(), `conformance-${name}-`));
        const store = newMemStore();
        const events: EventEnvelope[] = [];
        const { ctx, cancel } = Context.withDeadline(
          Context.background(),
          CTX_DEADLINE,
        );

        let conv: Conversation | undefined;
        try {
          conv = await Open(ctx, {
            harness: info.harness,
            binaryPath: info.path,
            workingDir: dir,
            store,
            inputPolicy: AutoAcceptTrust,
            // Attach the acquisition subsystem: a sink makes the plan pick the
            // reachable mode and routes any admitted events here.
            acquisitionMode: AcquisitionModeStream,
            onAcquisitionEvent: (env) => events.push(env),
          });

          // Drive the sentinel prompt through the same control/send seam chat
          // exposes to callers.
          const release = await conv.acquireControl(ctx);
          try {
            await conv.send(ctx, PROMPT);
          } finally {
            release();
          }

          const turn = await waitTerminal(ctx, conv);
          expect(
            turn.state,
            `${name}: turn errored: ${turn.reason ?? ""}`,
          ).toBe(TurnStateComplete);
          expect(turn.text.trim(), `${name}: empty assistant reply`).not.toBe(
            "",
          );

          // Session id captured EXACTLY once: the store record carries a stable,
          // non-empty harness session id, and a second read is byte-identical —
          // no double-write from the acquisition tap (StreamTap only READS it).
          const first = await store.getSession(conv.sessionID());
          expect(
            first.harnessSessionID,
            `${name}: harness session id was not captured`,
          ).not.toBe("");
          const second = await store.getSession(conv.sessionID());
          expect(second.harnessSessionID).toBe(first.harnessSessionID);
          // The live conversation view agrees with the persisted record.
          expect(conv.session.harnessSessionID).toBe(first.harnessSessionID);

          // Every delivered acquisition event must have been admissible under the
          // central authority filter for the LATCHED mode. For Off no event is
          // ever admitted (StreamTap goes inert), so this also asserts the sink
          // stayed silent; for Hooks it asserts the source/kind authority held.
          for (const env of events) {
            const source = (env.event.source ?? SourceLive) as "live" | "file";
            const isSubagent = (env.parentSessionID ?? "") !== "";
            expect(
              admitParent(latched, source, env.event.type ?? "", isSubagent),
              `${name}: event kind=${env.event.type} source=${source} was delivered but ` +
                `admitParent(${describeAcquisitionMode(latched)}) rejects it`,
            ).toBe(true);
            // Delivered events carry the run identity and the captured id.
            expect(env.runID).toBe(conv.sessionID());
            expect(env.harness).toBe(info.harness);
          }
          // In the Off latched mode the acquisition sink must stay silent — the
          // filter admits nothing, so no double-record leaks through.
          if (latched === AcquisitionModeOff) {
            expect(
              events.length,
              `${name}: Off mode delivered ${events.length} acquisition events; expected none`,
            ).toBe(0);
          }

          await conv.quit(ctx).catch(() => {});
        } finally {
          cancel();
          if (conv) {
            const { ctx: closeCtx } = Context.withDeadline(
              Context.background(),
              3000,
            );
            await conv.close(closeCtx).catch(() => {});
          }
          rmSync(dir, { recursive: true, force: true });
        }
      },
      TEST_TIMEOUT,
    );
  }
});

// ── Checks 1-2: harness permission-flag surface ───────────────────────────────
//
// Assert the REAL binaries still offer the flags and values the shipped
// permission code emits. Only claude-code and codex are covered: opencode and pi
// have no launch-time permission axis at all (effectiveLaunchRung's `default:`
// arm returns ""), so there is nothing to drift.
//
// DERIVE, DON'T RETYPE. Both the flag NAMES and the flag VALUES below come from
// the exported constants in src/wrapper/internal/permissionrungs.ts — the replay
// authority for these spellings, and therefore their natural home. A value
// retyped into this file would drift against the shipped map instead of against
// the CLI, which is the opposite of what this check is for.

/** How long a `--help` invocation may take before we call it hung. */
const HELP_TIMEOUT = 30_000;

/**
 * helpText runs `<binary> --help` and returns stdout+stderr.
 *
 * It takes the discovery Info, NOT a bare binary name: `info.path` is the
 * override-aware absolute path (HARNESS_BINARY_* / HARNESS_BINARY), so this
 * probes exactly the binary the other halves launch. A bare `claude` would
 * silently probe a different one.
 *
 * Called only from inside a test body, so the default (CONFORMANCE unset) run
 * spawns nothing.
 */
function helpText(info: Info): string {
  const res = spawnSync(info.path, ["--help"], {
    encoding: "utf8",
    timeout: HELP_TIMEOUT,
    maxBuffer: 32 * 1024 * 1024,
  });
  if (res.error) {
    throw new Error(
      `${info.harness}: could not run \`${info.path} --help\`: ${res.error.message}`,
    );
  }
  return `${res.stdout ?? ""}\n${res.stderr ?? ""}`;
}

/**
 * squash collapses every run of whitespace to a single space. Both CLIs
 * hard-wrap their choice lists at the detected terminal width, so a literal
 * match against the unwrapped rendering fails for reasons that have nothing to
 * do with drift.
 */
function squash(text: string): string {
  return text.replace(/\s+/g, " ");
}

/**
 * flagSection returns the slice of squashed --help starting at `flag`, so a
 * value is asserted against the flag's OWN entry rather than anywhere in the
 * help text (codex's `never` and `read-only` both occur in unrelated prose).
 * Returns "" when the flag is absent — the caller asserts presence first.
 *
 * The span is a deliberately GENEROUS fixed window, not a parse: the two CLIs
 * do not share a rendering (claude prints a one-line `(choices: …)`, codex's -s
 * a one-line `[possible values: …]` and its -a a bulleted prose list), so any
 * end-of-entry rule would be a third shape to keep in sync. The default covers
 * the longest rendering today (codex -a, ~490 chars) with room to grow, at the
 * cost of trailing into the next entry's prose — harmless unless that prose
 * happens to contain a value that was in fact removed, which the excerpt in the
 * failure message would show.
 */
function flagSection(help: string, flag: string, span = 800): string {
  const at = help.indexOf(flag);
  if (at < 0) return "";
  return help.slice(at, at + span);
}

/** A short, quotable excerpt of the flag's help entry for a drift report. */
function excerpt(help: string, flag: string): string {
  const section = flagSection(help, flag, 320);
  return section === "" ? "(flag absent from --help)" : section.trim();
}

const SYMBOLS = "src/wrapper/internal/permissionrungs.ts";

describe("conformance: permission-flag surface (CONFORMANCE=1)", () => {
  // ── Check 1: claude --help still offers --permission-mode + its values ─────

  {
    const info = infos["claude-code"];
    const skip = !CONFORMANCE || !info.installed;

    test.skipIf(skip)(
      `claude-code: --help offers ${ClaudePermissionModeFlag} with every mapped value, plus the bypass flags`,
      () => {
        const help = squash(helpText(info));
        const version = info.detectedVersion || "?";

        // The values claude must still accept. TWO classes, both load-bearing:
        //
        //  - EMITTABLE — what argsWithHarnessPermissionMode actually puts on
        //    argv: "plan", "manual", "acceptEdits" (the ask rung), "auto",
        //    "bypassPermissions" (the bypass rung);
        //  - RECOGNIZED-BUT-NOT-EMITTED — "dontAsk". We never emit it, but a
        //    caller may pass it and isSupportedPermissionMode accepts it. It is
        //    OFF the canonical ladder: claudeRung returns "" for it and it has
        //    no footer, so it is a spelling we recognize, not a rung.
        //
        // Derived as: the three exported claude-native spellings ∪ the canonical
        // rungs claude spells identically. NOT permissionRungs(), which returns
        // the canonical vocabulary — claude accepts neither "ask" nor "bypass".
        const derived = [
          ClaudeModeAcceptEdits,
          ClaudeModeDontAsk,
          ClaudeModeBypassPermissions,
          PermissionModePlan,
          PermissionModeManual,
          PermissionModeAuto,
        ];
        // Cross-check against the shipped input predicate (META-HARNESS-100):
        // every derived spelling must still be an accepted input, or the two
        // halves of the shipped map have already diverged from each other.
        const expected = derived.filter((v) =>
          isSupportedPermissionMode("claude-code", v),
        );
        expect(
          expected,
          `claude-code: isSupportedPermissionMode rejects ${derived
            .filter((v) => !isSupportedPermissionMode("claude-code", v))
            .join(", ")} — the derived --help expectation and the shipped ` +
            `permission map (src/wrapper/internal/permission.ts) disagree`,
        ).toEqual(derived);

        expect(
          help.includes(ClaudePermissionModeFlag),
          `claude ${version} no longer offers \`${ClaudePermissionModeFlag}\` ` +
            `(expected from ClaudePermissionModeFlag, ${SYMBOLS}); \`--help\` no longer ` +
            `mentions it at all. The whole claude permission axis has been renamed — ` +
            `update claudePermissionValue/claudeGuardFlags in ` +
            `src/wrapper/internal/permission.ts and effectiveLaunchRung in ${SYMBOLS}.`,
        ).toBe(true);

        const section = flagSection(help, ClaudePermissionModeFlag);
        for (const value of expected) {
          // The choice list is rendered with quotes: (choices: "acceptEdits", …).
          expect(
            section.includes(`"${value}"`),
            `claude ${version} no longer accepts \`${ClaudePermissionModeFlag} ${value}\` ` +
              `(expected from ${SYMBOLS}); \`--help\` now shows: ` +
              `${excerpt(help, ClaudePermissionModeFlag)} . Update the claude arm of ` +
              `claudePermissionValue/argsWithHarnessPermissionMode in ` +
              `src/wrapper/internal/permission.ts and claudeRung in ${SYMBOLS}.`,
          ).toBe(true);
        }

        // The blanket bypass flags the SHIPPED code path already injects:
        // metaHarnessArgs (src/cli/structured-runner.ts) adds
        // --dangerously-skip-permissions under --sandbox-defaults today.
        for (const flag of ClaudeSkipPermissionsFlags) {
          expect(
            help.includes(flag),
            `claude ${version} no longer offers \`${flag}\` (expected from ` +
              `ClaudeSkipPermissionsFlags, ${SYMBOLS}); \`--help\` no longer mentions it. ` +
              `Launching with it now hard-errors — update ClaudeSkipPermissionsFlags, ` +
              `claudeGuardFlags (src/wrapper/internal/permission.ts) and metaHarnessArgs ` +
              `(src/cli/structured-runner.ts).`,
          ).toBe(true);
        }
      },
      HELP_TIMEOUT + 10_000,
    );
  }

  // ── Check 2: codex --help still offers -s/-a with their emitted values ─────

  {
    const info = infos["codex"];
    const skip = !CONFORMANCE || !info.installed;

    test.skipIf(skip)(
      "codex: --help offers -s/--sandbox, -a/--ask-for-approval, -p/--profile and the bypass flag with every emitted value",
      () => {
        const help = squash(helpText(info));
        const version = info.detectedVersion || "?";

        // clap renders a short/long pair as `-s, --sandbox`; deriving the
        // rendering from the exported flag arrays keeps both spellings asserted
        // without matching a bare `-s` (which occurs all over the help text).
        const sandboxFlag = CodexSandboxFlags.join(", ");
        const approvalFlag = CodexApprovalFlags.join(", ");
        const profileFlag = CodexProfileFlags.join(", ");

        // The two axes do NOT share a help shape at 0.144.5: -s renders a
        // one-line `[possible values: …]`, while -a renders a bulleted prose
        // list ("- on-request: The model decides …"). A `[possible values:`
        // matcher applied to -a fails, so assert PER VALUE against the flag's
        // own squashed section instead of against a joined list literal.
        const axes: {
          flag: string;
          short: string;
          symbol: string;
          values: { value: string; symbol: string }[];
        }[] = [
          {
            flag: sandboxFlag,
            short: CodexSandboxFlags[0],
            symbol: "CodexSandboxFlags",
            values: [
              { value: CodexSandboxReadOnly, symbol: "CodexSandboxReadOnly" },
              {
                value: CodexSandboxWorkspaceWrite,
                symbol: "CodexSandboxWorkspaceWrite",
              },
              {
                value: CodexSandboxDangerFullAccess,
                symbol: "CodexSandboxDangerFullAccess",
              },
            ],
          },
          {
            flag: approvalFlag,
            short: CodexApprovalFlags[0],
            symbol: "CodexApprovalFlags",
            values: [
              {
                value: CodexApprovalUntrusted,
                symbol: "CodexApprovalUntrusted",
              },
              {
                value: CodexApprovalOnRequest,
                symbol: "CodexApprovalOnRequest",
              },
              { value: CodexApprovalNever, symbol: "CodexApprovalNever" },
            ],
          },
        ];

        for (const axis of axes) {
          expect(
            help.includes(axis.flag),
            `codex ${version} no longer offers \`${axis.flag}\` (expected from ` +
              `${axis.symbol}, ${SYMBOLS}); \`--help\` no longer renders that pair. ` +
              `Update codexPermissionArgs/codexGuardFlags ` +
              `(src/wrapper/internal/permission.ts) and codexLaunchRung in ${SYMBOLS}.`,
          ).toBe(true);

          const section = flagSection(help, axis.flag);
          for (const { value, symbol } of axis.values) {
            expect(
              section.includes(value),
              `codex ${version} no longer accepts \`${axis.short} ${value}\` ` +
                `(expected from ${symbol}, ${SYMBOLS}); \`--help\` now shows: ` +
                `${excerpt(help, axis.flag)} . Update the forward map in ${SYMBOLS} ` +
                `and argsWithHarnessPermissionMode in src/wrapper/internal/permission.ts.`,
            ).toBe(true);
          }
        }

        // The blanket bypass flag effectiveLaunchRung resolves to `bypass`.
        expect(
          help.includes(CodexBypassFlag),
          `codex ${version} no longer offers \`${CodexBypassFlag}\` (expected from ` +
            `CodexBypassFlag, ${SYMBOLS}); \`--help\` no longer mentions it. Update ` +
            `CodexBypassFlag and codexGuardFlags (src/wrapper/internal/permission.ts).`,
        ).toBe(true);

        // -p/--profile is guarded but never emitted: its PRESENCE is what makes
        // effectiveLaunchRung report "" (unknowable posture), because a profile
        // fills in whichever axis the caller left unset. If codex drops it, the
        // guard becomes dead weight; if codex reuses `-p` for something else the
        // guard becomes actively wrong — either way we must hear about it.
        expect(
          help.includes(profileFlag),
          `codex ${version} no longer offers \`${profileFlag}\` (expected from ` +
            `CodexProfileFlags, ${SYMBOLS}); \`--help\` no longer renders that pair. ` +
            `The unknowable-posture guard in codexLaunchRung (${SYMBOLS}) and ` +
            `codexGuardFlags (src/wrapper/internal/permission.ts) must be re-derived — ` +
            `note claude's -p is --print, so the two harnesses must stay asymmetric.`,
        ).toBe(true);
      },
      HELP_TIMEOUT + 10_000,
    );
  }
});

// ── Check 4: codex `/status` row assertions ───────────────────────────────────
//
// Checks 1-2 above prove the codex permission FLAGS still exist on `--help`.
// This check proves the other end of the same wire: that a session actually
// LAUNCHED with those flags still RENDERS the posture back, in the rows the
// shipped parser reads. A `--help` entry can survive a rename of the row that
// reports it, and vice versa — only a live launch closes the loop.
//
// MECHANICS — launch and scrape. Nothing is sent. Conversation.primeSessionID
// already writes CodexAdapter.primeSessionIDKeys() (literally `/status` plus the
// CSI 13u submit) BEFORE Open returns, gated on cols >= CODEX_STATUS_MIN_COLS
// (60; the suite's default 120 clears it). So this check REUSES that prime — it
// polls screenSnapshot() on the freshly-opened conversation until the box
// settles (see PRIME_BOUND / STATUS_PAINT_BOUND) and never writes a second
// `/status`, which would need control-token acquisition and would duplicate that
// machinery for nothing.
//
// NEVER DRIVE `/permissions`. Selecting a preset in that dialog writes
// ~/.codex/config.toml GLOBALLY — running the test suite would mutate the
// developer's own approval settings as a side effect (see
// test/corpus/codex/permissions-dialog/meta.json, which records that Enter was
// never pressed for exactly this reason). Reading `/status` is safe; selecting
// is not. This check reads only.
//
// COVERAGE THIS CHECK DOES *NOT* GIVE YOU. The live launch exercises exactly ONE
// cell of the (sandbox, approval) → rung forward map in
// src/wrapper/internal/permissionrungs.ts (~:248-272): the
// `workspace-write` × `on-request` pair. The other cells — every `read-only`
// spelling, `-a never`, `--dangerously-bypass-…` — have NO live coverage here
// and rest on the recorded corpus (test/corpus/codex/status-*) plus checks 1-2,
// which only prove the VALUES still appear in `--help`. A codex release that
// kept every flag but re-spelled `Custom (workspace, never)` would sail past
// this file. Widening the matrix means one launch per rung, ~15-30 s each,
// serial (fileParallelism: false) — a deliberate budget call, not an oversight.

/**
 * primeOutcomeOf reads Conversation's PRIVATE `primeOutcome` field.
 *
 * conversation.ts (~:458-476) documents it as "NOT a public accessor … tests
 * read it via a structural escape"; this is that escape, the same shape used by
 * test/chat/codex_prime_sessionid.test.ts and codex_locate_sessionid.test.ts.
 * Reading it is load-bearing here, not diagnostic — see WROTE_STATUS below.
 */
function primeOutcomeOf(c: Conversation): string | undefined {
  return (c as unknown as { primeOutcome?: string }).primeOutcome;
}

/**
 * The primeSessionID outcomes that mean "`/status` WAS written to the composer".
 *
 * primeSessionID records five. Guarding on `!== "too_narrow"` is WRONG and
 * produces fabricated drift reports: `not_written` fires (conversation.ts
 * ~:1423) when awaitPromptReadyUntil deadlines before the composer is ready,
 * which is exactly what a fresh CODEX_HOME produces when codex paints its
 * first-run / migration screen (codexMigrationAnchor / codexUpdateAnchor,
 * src/chat/ready.ts ~:36-38, both pinned not-ready). Under a naive guard a
 * healthy binary that merely showed a migration notice would be reported as
 * "the Collaboration mode: row is gone".
 *
 * So: these three ⇒ proceed. `too_narrow` / `not_written` / undefined ⇒ the
 * PRECONDITION was not met, which is a SKIP, never a failure.
 */
const WROTE_STATUS = new Set([
  "captured",
  "written_uncaptured",
  "persist_failed",
]);

/**
 * The codex startup-banner literal, copied — not imported.
 *
 * statusBoxHeaderRE (src/turns/harness/codex.ts:67) is module-private and stays
 * that way: exporting a regex purely so a test can reach it widens the adapter's
 * surface for no production caller. extractSessionID (~:204) gates on this same
 * literal, and src/chat/permission.ts spells it out as `codexStatusHeader` for
 * the same reason.
 */
const CODEX_BANNER = ">_ OpenAI Codex (v";

/**
 * The prime deadline this check launches with (Options.primeBound, the
 * documented test-only override at conversation.ts ~:198).
 *
 * The PRODUCTION default is primeBoundGap = 800 ms (conversation.ts ~:311),
 * deliberately tight so Open can never hang on the scrape. A cold codex against
 * a FRESH CODEX_HOME does not reach a ready composer inside it: measured live on
 * 2026-07-23 against 0.144.5, `awaitPromptReadyUntil` deadlines and
 * primeSessionID records `not_written`, so `/status` is never typed and the box
 * never renders. Under the default this check would therefore SKIP on every run
 * — technically correct, permanently useless.
 *
 * Widening the bound HERE (and only here) is the honest fix: it changes how long
 * the test is willing to wait, never what it asserts. It cannot manufacture a
 * pass — a binary that stopped rendering the box still fails, just later.
 */
const PRIME_BOUND = 30_000;

/**
 * How long to poll for the fully-painted `/status` box after Open returns.
 *
 * primeSessionID exits as soon as BOTH the session id and the mode-box parse
 * land, and `Permissions:` parses two rows ABOVE `Collaboration mode:` in a box
 * that paints top-down — so Open can legitimately return on a frame where the
 * collaboration row has not arrived. The META-HARNESS-155 probe recorded exactly
 * that: the prime-time cached reading came back `collaboration: "unknown"` on
 * all three launches it drove, while a replay of the completed frame parses
 * `default`. Reading ONCE the instant Open returns would assert against a
 * half-painted box, so poll the live screen until it settles.
 */
const STATUS_PAINT_BOUND = 30_000;
const STATUS_POLL_INTERVAL = 250;

/**
 * rowText finds a rendered `/status` row for a label, for the FAILURE REPORT
 * ONLY — never for an assertion. The assertions route through
 * parsePermissionMode so the test cannot stay green while the shipped parser
 * rots; this is just "show me what was actually on screen".
 */
function rowText(text: string, label: string): string {
  for (const line of text.split("\n")) {
    if (line.includes("│") && line.includes(label)) return line.trim();
  }
  return `row absent (no line containing "${label}")`;
}

/**
 * redactAccount masks the `Account:` row's value in the screen dump.
 *
 * The failure report prints the WHOLE screen, and the live box carries the
 * running operator's ChatGPT login — which would land verbatim in CI logs on any
 * red run. test/corpus/codex/status-box/meta.json records the same redaction for
 * the recorded bytes ("the ONLY edit to bytes.raw"); this is the live analogue.
 * Column-preserving so the surrounding box still lines up, and no assertion
 * reads this row, so masking it costs the report nothing.
 */
function redactAccount(text: string): string {
  return text.replace(
    /^(\s*│\s+Account:\s+)(\S[^│]*?)(\s*│.*)$/gm,
    (_m, head: string, value: string, tail: string) =>
      head +
      "<redacted>".padEnd(value.length, " ").slice(0, value.length) +
      tail,
  );
}

describe("conformance: codex /status rows (CONFORMANCE=1)", () => {
  const info = infos.codex;
  const skip = !CONFORMANCE || !info.installed;

  // Derived from the replay authority, never retyped — same discipline as
  // checks 1-2. These are the flags the launch below actually passes.
  const LAUNCH_ARGS = [
    CodexSandboxFlags[0],
    CodexSandboxWorkspaceWrite,
    CodexApprovalFlags[0],
    CodexApprovalOnRequest,
  ];

  test.skipIf(skip)(
    `codex: live /status renders Collaboration mode: and Permissions: for \`${LAUNCH_ARGS.join(" ")}\``,
    async (t) => {
      const version = info.detectedVersion || "?";

      // Both axes of the launch must normalize to the SAME rung, or the
      // expectation below is ill-formed. workspace-write and on-request are both
      // `acceptEdits`; asserting their agreement here means a future edit to
      // either arm of normalizePermissionRung fails loudly instead of silently
      // re-pointing what this check expects.
      const expectedRung: PermissionRung | undefined = normalizePermissionRung(
        CodexSandboxWorkspaceWrite,
        "codex",
      );
      const byApproval = normalizePermissionRung(
        CodexApprovalOnRequest,
        "codex",
      );
      expect(
        expectedRung,
        `codex: normalizePermissionRung disagrees across the launch axes — ` +
          `${CodexSandboxWorkspaceWrite} → ${expectedRung ?? "undefined"}, ` +
          `${CodexApprovalOnRequest} → ${byApproval ?? "undefined"} (src/chat/permission.ts). ` +
          `This check's expectation is derived from them, so it cannot be formed while they ` +
          `disagree.`,
      ).toBe(byApproval);
      expect(
        expectedRung,
        `codex: normalizePermissionRung no longer maps the launch spelling ` +
          `${CodexSandboxWorkspaceWrite} to any ladder rung (src/chat/permission.ts) — the ` +
          `codex arm of the normalizer has lost the entry this check derives from.`,
      ).not.toBeUndefined();

      // Isolate CODEX_HOME. Options.env flows through cleanHarnessEnv verbatim
      // (minus claude nesting markers) and envToRecord (src/wrapper/internal/
      // run.ts ~:28-40) is LAST-WINS, so appending the override is enough.
      //
      // ONLY auth.json is copied in from the real ~/.codex — auth lives there
      // and a bare fresh dir lands on the sign-in wall. config.toml is
      // deliberately NOT copied, so the /status reading reflects the LAUNCH
      // FLAGS rather than the developer's own approval settings, and nothing
      // this suite runs can write the developer's config. (test/corpus/codex/*/
      // meta.json already records "clean CODEX_HOME" recordings — established
      // practice.) HOME isolation is NOT viable: a fresh HOME lands the CLI on
      // the onboarding wall, where no conformance fact is observable.
      const codexHome = mkdtempSync(join(tmpdir(), "conformance-codex-home-"));
      const realAuth = join(homedir(), ".codex", "auth.json");
      if (existsSync(realAuth)) {
        copyFileSync(realAuth, join(codexHome, "auth.json"));
      }
      const env = [
        ...Object.entries(process.env).map(([k, v]) => `${k}=${v ?? ""}`),
        `CODEX_HOME=${codexHome}`,
      ];

      const dir = mkdtempSync(join(tmpdir(), "conformance-codex-status-"));
      const { ctx, cancel } = Context.withDeadline(
        Context.background(),
        CTX_DEADLINE,
      );

      // Fail-fast observer. The sampled wrapper Snapshot (src/wrapper/internal/
      // session.ts ~:52-57) carries status + reason, so a terminal status aborts
      // the poll immediately instead of burning the full deadline — that is what
      // turns "no row after 240 s" into "codex exited: unexpected argument".
      let fatal = "";
      const TERMINAL: string[] = [
        StatusFailed,
        StatusBinaryNotFound,
        StatusInterrupted,
      ];

      let conv: Conversation | undefined;
      let captured: string | undefined;
      let prime: string | undefined;
      try {
        conv = await Open(ctx, {
          harness: "codex",
          binaryPath: info.path,
          workingDir: dir,
          env,
          args: LAUNCH_ARGS,
          store: newMemStore(),
          inputPolicy: AutoAcceptTrust,
          primeBound: PRIME_BOUND,
          activityInterval: 250,
          onActivity: (snap) => {
            if (fatal === "" && TERMINAL.includes(snap.status)) {
              fatal = `${snap.status}${snap.reason ? `: ${snap.reason}` : ""}`;
            }
          },
        });

        prime = primeOutcomeOf(conv);

        // Poll the LIVE screen until the box is fully painted (or the binary
        // dies, or the bound elapses). screenSnapshot() must be read BEFORE
        // close(): the Screen object outlives the session, but the wrapper
        // snapshot does not — close() takes the final sample itself
        // (conversation.ts ~:604-607).
        const until = Date.now() + STATUS_PAINT_BOUND;
        for (;;) {
          const frame = conv.screenSnapshot().text;
          captured = frame;
          const reading = parsePermissionMode(frame, "codex");
          const painted =
            frame.includes(CODEX_BANNER) &&
            reading !== null &&
            reading.collaboration !== "unknown" &&
            (reading.raw ?? "") !== "";
          if (painted || fatal !== "" || Date.now() >= until) break;
          await new Promise((r) => setTimeout(r, STATUS_POLL_INTERVAL));
        }
      } finally {
        cancel();
        if (conv) {
          const { ctx: closeCtx } = Context.withDeadline(
            Context.background(),
            3000,
          );
          await conv.close(closeCtx).catch(() => undefined);
        }
        rmSync(dir, { recursive: true, force: true });
        rmSync(codexHome, { recursive: true, force: true });
      }

      // `captured` is always assigned by the poll loop: the only path that skips
      // it is Open itself throwing, and that throw propagates past here.
      const text = captured;

      // The screen scrape every failure below quotes. Naming the launch flags,
      // the prime outcome and where to re-record is an ACCEPTANCE CRITERION of
      // this check: a bare `expected 'default' to be 'unknown'` tells the next
      // reader nothing about which of the half-dozen preconditions moved.
      const report =
        `codex ${version} LIVE /status DRIFT.\n` +
        `  launch flags:   ${LAUNCH_ARGS.join(" ")}\n` +
        `  prime outcome:  ${prime ?? "(none — primeSessionID never recorded one)"}\n` +
        `  session status: ${fatal === "" ? "healthy" : fatal}\n` +
        `  Collaboration:  ${rowText(text, "Collaboration mode:")}\n` +
        `  Permissions:    ${rowText(text, "Permissions:")}\n` +
        `  box header:     ${text.includes(CODEX_BANNER) ? "present" : "ABSENT"}\n` +
        `  Re-record the box with test/corpus/tools/record-pty.ts into ` +
        `test/corpus/codex/status-box/ and re-derive the row regexes in ` +
        `src/chat/permission.ts against src/turns/harness/codex.ts.\n` +
        `  --- screen ---\n${redactAccount(text)}\n  --- end screen ---`;

      // A dead session is never a row-drift finding — say what actually killed
      // it. The PTY captured codex's own stderr, so a rejected flag reports
      // `error: unexpected argument …` right here.
      expect(
        fatal,
        `codex ${version}: session died before the box painted.\n${report}`,
      ).toBe("");

      // Resolve the header/prime ambiguity EXPLICITLY. `captured` does not imply
      // the box is on screen: extractSessionID tries resumeRE (codex.ts ~:49)
      // FIRST (~:202), and captureFromScreen is called check-before-wait
      // (conversation.ts ~:1439) — so a `codex resume <uuid>` string anywhere on
      // screen yields `captured` with no box rendered.
      //
      //   header absent + prime in the wrote set → FAIL (the box regressed —
      //     `/status` was typed and submitted and nothing came back),
      //   header absent + prime not in the wrote set → SKIP (the composer was
      //     never ready, so `/status` was never written; a precondition, not
      //     drift).
      //
      // When the header IS present the box is on screen and the assertions run
      // regardless of the prime outcome — the box itself is the precondition
      // this check needs, and the prime outcome is only how we tell "absent
      // because it regressed" from "absent because we never asked".
      if (!text.includes(CODEX_BANNER)) {
        if (!WROTE_STATUS.has(prime ?? "")) {
          t.skip(
            `codex ${version}: /status was never written (primeSessionID outcome ` +
              `${prime ?? "none"}) — the composer was not ready, so there is no box to ` +
              `assert against. Precondition, not drift.`,
          );
          return;
        }
        expect(
          text.includes(CODEX_BANNER),
          `codex ${version}: \`/status\` WAS written (prime outcome ${prime ?? "none"}) but ` +
            `the box header \`${CODEX_BANNER}\` never appeared within ` +
            `${String(STATUS_PAINT_BOUND)} ms. The status box has regressed or been ` +
            `renamed.\n${report}`,
        ).toBe(true);
      }

      const reading = parsePermissionMode(text, "codex");
      if (reading === null) {
        // Thrown, not expect()ed, so the narrowing survives into the assertions
        // below — parsePermissionMode returning null means the codex arm of
        // src/chat/permission.ts is gone, which is drift in its own right.
        throw new Error(
          `codex ${version}: parsePermissionMode returned null for harness "codex" — the ` +
            `codex arm of src/chat/permission.ts has been removed.\n${report}`,
        );
      }

      // ── A. `Collaboration mode:` — the hard anchor ─────────────────────────
      //
      // Corroborated in the 0.144.5 binary's string table, and the row
      // META-HARNESS-102's collaboration reading depends on. The launch below
      // never runs `/plan`, so the value is `Default`.
      //
      // Asserted through the SHIPPED parser's `collaboration` field, not against
      // a whole line: the box renders at newScreen(120, 40) and its width tracks
      // the longest value (the cwd-dependent `Directory:` row), so a whole-line
      // literal would make this a width flake rather than a drift check.
      expect(
        reading.collaboration,
        `codex ${version}: the \`Collaboration mode:\` row did not parse as \`Default\` for a ` +
          `launch that never ran \`/plan\`. Expected collaboration "default", got ` +
          `"${reading.collaboration ?? "undefined"}".\n${report}`,
      ).toBe("default");

      // ── B. `Permissions:` — present, and it tracks the launch flags ────────
      //
      // The META-HARNESS-155 pre-flight probe (2026-07-23, codex-cli 0.144.5)
      // FOUND this row, refuting the epic's premise that it might be absent — so
      // it is asserted, not merely observed. The probe also showed the row DOES
      // track launch posture (`-s read-only -a never` renders `Read Only
      // (never)`), while the pair used here happens to equal codex's own default
      // presentation, `Workspace (Ask for approval)`.
      //
      // The value goes through parsePermissionMode rather than being
      // string-matched. That is the whole point: a test carrying its own copy of
      // the row's shape would stay green while the SHIPPED parser rotted, which
      // is precisely the failure this ticket exists to prevent.
      expect(
        reading.observed,
        `codex ${version}: the \`Permissions:\` row no longer reads back the launched rung. ` +
          `Expected observed "${expectedRung ?? "undefined"}" (derived from normalizePermissionRung ` +
          `${CodexSandboxWorkspaceWrite}/${CodexApprovalOnRequest}), got "${reading.observed}" ` +
          `from raw "${reading.raw ?? ""}". Either codex re-spelled the value — add the new ` +
          `spelling to codexPermissionRungs in src/chat/permission.ts and re-record ` +
          `test/corpus/codex/status-* — or the (sandbox, approval) → rung forward map in ` +
          `${SYMBOLS} (~:248-272) no longer matches what codex actually applies, which is a ` +
          `SILENT MIS-REPORT of the launch posture.\n${report}`,
      ).toBe(expectedRung);

      // The reading must come from the box, not from a prime-outcome fallback.
      expect(
        reading.source,
        `codex ${version}: expected the reading's source to be "status" (a live box parse), ` +
          `got "${reading.source}".\n${report}`,
      ).toBe("status");
    },
    TEST_TIMEOUT,
  );
});

// ── Check 5: claude live permission-mode footers ──────────────────────────────
//
// The SILENT-RENAME CATCHER, and the claude counterpart of check 4. Checks 1-2
// prove claude still ACCEPTS `--permission-mode <value>`; this check proves it
// still REPORTS the resulting posture in the footer the shipped parser reads.
//
// The two failure modes are not symmetric, which is the whole reason this check
// is separate from checks 1-2:
//
//   - The FLAG surface degrades LOUDLY but LATE: a renamed flag makes claude
//     exit with `error: unexpected argument`, but only once a caller actually
//     launches with that mode, in production.
//   - The DETECTION path degrades SILENTLY: a renamed footer means
//     parsePermissionMode reports `observed: "unknown"` (or, worse, keeps
//     reporting a stale rung) with no error raised anywhere. A caller comparing
//     `requested` to `observed` sees permanent unresolvable drift, or none at
//     all, and nothing says why.
//
// And these strings really do move. claude's `manual` footer is the ONLY one
// lacking the `(shift+tab to cycle)` suffix — a detail that exists in
// src/chat/permission.ts purely because someone looked; claude flipped its
// DEFAULT permission mode to Manual; the installed binary moved 2.1.217 →
// 2.1.218 during this plan's own review. Unit tests over the recorded corpus
// (test/chat/permission.test.ts, replaying test/corpus/claude-code/
// permission-modes/*) cannot catch any of that — the fixtures are frozen bytes
// and keep passing forever after the real CLI has moved on.
//
// MECHANICS — launch, poll, close. NOTHING IS SENT. startPumps runs inside Open
// before it returns, and the trust / "Bypass Permissions mode" dialogs are
// resolved by handleInputRequested → tryResolveInput from `inputPolicy` with no
// turn in flight. So each case is launch → poll readyForInput + the footer parse
// → scrape → close(): six launches, ZERO model calls, zero quota burn. It also
// sidesteps the "which mode is default" question entirely — five of the six
// cases NAME the mode they launch at.
//
// ONE test() PER MODE, deliberately not one test looping six launches. A shared
// loop body would let the first failure hide the other five, and six cold claude
// launches blow any single test budget (fileParallelism: false makes these
// strictly serial — they are the dominant cost of this file). `manual` in
// particular MUST stand alone: it is the one footer without the
// `(shift+tab to cycle)` suffix, so a suffix-requiring regex regression in
// parsePermissionMode has to fail loudly rather than be masked by a sibling.
//
// `dontAsk` is NOT here. It is flag-surface only: claudeRung returns "" for it,
// it is off the canonical ladder and it paints no footer. Check 1 covers it.
//
// SIDE EFFECT. These launches touch ~/.claude.json exactly as half 2 does (a
// `projects` entry per working dir plus `hasTrustDialogAccepted`, which
// AutoAcceptTrust exists precisely to answer — i.e. persist). The
// bypassPermissions launch does the same on a not-yet-accepted machine. HOME
// isolation is NOT viable: a fresh HOME lands claude on the onboarding wall,
// where no footer is observable. See this file's header comment.

/** How long to poll for a painted footer after Open returns. */
const FOOTER_PAINT_BOUND = 60_000;
const FOOTER_POLL_INTERVAL = 250;

/** Where the claude footer parse lives, for every remediation pointer below. */
const FOOTER_PARSER = "src/chat/permission.ts";

/** The corpus fixture the failure reports tell the next reader to re-record. */
const FOOTER_CORPUS = "test/corpus/claude-code/permission-modes/";

/**
 * The five live footer cases, derived from META-HARNESS-99's live-probed table.
 *
 * DERIVE, DON'T RETYPE — same discipline as checks 1-2 and 4. The launch
 * spellings come from the exported constants in permissionrungs.ts (the replay
 * authority), and the EXPECTED RUNG is computed by running that same spelling
 * through the shipped normalizePermissionRung rather than being written down
 * here. A hand-written expectation would drift against the shipped map instead
 * of against the CLI, which is the opposite of what this check is for.
 *
 * `fragment` is the leading footer text. It is used for the FAILURE REPORT and
 * for nothing else — the load-bearing assertion routes through
 * parsePermissionMode, so this file carries no second copy of the footer shape.
 * A test with its own regex would stay green while the shipped parser rotted.
 */
const CLAUDE_FOOTER_CASES: readonly { mode: string; fragment: string }[] = [
  { mode: PermissionModeAuto, fragment: "auto mode on" },
  { mode: PermissionModeManual, fragment: "manual mode on" },
  { mode: ClaudeModeAcceptEdits, fragment: "accept edits on" },
  { mode: PermissionModePlan, fragment: "plan mode on" },
  { mode: ClaudeModeBypassPermissions, fragment: "bypass permissions on" },
];

/**
 * The rung vocabulary the flagless case accepts, derived from the five launch
 * spellings above through the shipped normalizer — never retyped.
 *
 * NOT permissionRungs() (src/wrapper/internal/permissionrungs.ts ~:87-95): that
 * is the WRAPPER ladder, whose middle rung is spelled `ask`, while the parser
 * this check asserts through returns the chat-side `PermissionRung`, whose
 * middle rung is claude's native `acceptEdits`. The two vocabularies are
 * deliberately distinct (normalizePermissionRung is the bridge), so building the
 * accepted set out of the wrapper list would reject a perfectly healthy
 * `accept edits on` default. Deriving it from the normalizer keeps this check
 * pinned to the vocabulary the parser actually speaks.
 */
const CLAUDE_KNOWN_RUNGS: readonly (PermissionRung | undefined)[] =
  CLAUDE_FOOTER_CASES.map((c) =>
    normalizePermissionRung(c.mode, "claude-code"),
  );

/**
 * glyphLine returns the LAST footer-glyph line on screen, for the FAILURE REPORT
 * ONLY — never for an assertion.
 *
 * Last-wins mirrors parseClaudeFooter's own rule (the footer is the bottom-most
 * line; scrollback renders above it). The glyph set is copied, not imported:
 * claudeModeFooterRE / claudeModeGlyphRE are module-private in
 * src/chat/permission.ts and stay that way — exporting a regex purely so a test
 * can reach it would widen the parser's surface for no production caller, and
 * this is a report string, not a check.
 */
function glyphLine(text: string): string {
  let found = "";
  for (const line of text.split("\n")) {
    if (/[⏵⏸]/.test(line)) found = line.trim();
  }
  return found === "" ? "no glyph line" : found;
}

/** What one live launch observed. `text` is the last frame read before close(). */
interface FooterScrape {
  text: string;
  /** Non-empty when the wrapper reported a terminal status — the session died. */
  fatal: string;
  /** Whether readyForInput ever went true on this session. */
  ready: boolean;
}

/**
 * launchAndScrape opens claude with `args`, polls the live screen until the
 * footer parses, then closes. No prompt is ever sent.
 *
 * FAIL FAST ON A REJECTED FLAG. Without the onActivity observer a bad flag turns
 * an `unexpected argument` exit into a 240 s deadline hang with no diagnosis.
 * The sampled wrapper Snapshot (src/wrapper/internal/session.ts ~:52-57) carries
 * status + reason, so a terminal status aborts the poll immediately and the
 * caller's report reads `error: unexpected argument '--permission-mode' found`
 * instead of "no footer after 240 s".
 *
 * screenSnapshot() is read INSIDE the loop, i.e. strictly BEFORE close(): the
 * Screen object outlives the session but the wrapper snapshot does not — close()
 * takes the final sample itself (conversation.ts ~:604-607).
 *
 * If Open itself throws (claude exiting before the PTY bridge is up), the throw
 * propagates with the wrapper's own reason attached; there is no screen to
 * quote in that case because no session was ever established.
 */
async function launchAndScrape(
  info: Info,
  args: string[],
): Promise<FooterScrape> {
  const dir = mkdtempSync(join(tmpdir(), "conformance-claude-footer-"));
  const { ctx, cancel } = Context.withDeadline(
    Context.background(),
    CTX_DEADLINE,
  );

  let fatal = "";
  const TERMINAL: string[] = [
    StatusFailed,
    StatusBinaryNotFound,
    StatusInterrupted,
  ];

  let conv: Conversation | undefined;
  let captured: string | undefined;
  let ready = false;
  try {
    conv = await Open(ctx, {
      harness: "claude-code",
      binaryPath: info.path,
      workingDir: dir,
      store: newMemStore(),
      // Options.args (conversation.ts ~:127) already reaches launch, so this
      // check needs no new plumbing. It is also not caught by
      // firstSessionControlConflict: claude's sessionControlFlags() bans
      // --session-id / --resume / -c, but not --permission-mode.
      args,
      // Answers BOTH the folder-trust dialog and the "Bypass Permissions mode"
      // dialog — both pinned not-ready by claudeBlockingDialog (src/chat/
      // ready.ts ~:17, ~:25-31), so without a policy the poll below would
      // deadlock behind them rather than ever seeing a footer.
      inputPolicy: AutoAcceptTrust,
      activityInterval: 250,
      onActivity: (snap) => {
        if (fatal === "" && TERMINAL.includes(snap.status)) {
          fatal = `${snap.status}${snap.reason ? `: ${snap.reason}` : ""}`;
        }
      },
    });

    const until = Date.now() + FOOTER_PAINT_BOUND;
    for (;;) {
      const frame = conv.screenSnapshot().text;
      captured = frame;
      if (readyForInput("claude-code", frame)) ready = true;
      // Settle on a POSITIVE parse, not merely on a glyph: a renamed footer
      // keeps painting a glyph line, and breaking on that would race the
      // assertion against a half-painted frame. A rename therefore costs the
      // full bound and then reports — the slow path is the rare one.
      const parsed = parsePermissionMode(frame, "claude-code")?.source;
      if (
        (ready && parsed === "footer") ||
        fatal !== "" ||
        Date.now() >= until
      ) {
        break;
      }
      await new Promise((r) => setTimeout(r, FOOTER_POLL_INTERVAL));
    }
  } finally {
    cancel();
    if (conv) {
      const { ctx: closeCtx } = Context.withDeadline(
        Context.background(),
        3000,
      );
      await conv.close(closeCtx).catch(() => undefined);
    }
    rmSync(dir, { recursive: true, force: true });
  }
  // `captured` is always assigned by the poll loop: the only path that skips it
  // is Open itself throwing, and that throw propagates past here.
  return { text: captured ?? "", fatal, ready };
}

describe("conformance: claude permission-mode footers (CONFORMANCE=1)", () => {
  const info = infos["claude-code"];
  const skip = !CONFORMANCE || !info.installed;

  /**
   * The screen scrape every failure below quotes. This is an ACCEPTANCE
   * CRITERION of check 5, not a nicety: a bare `expected 'unknown' to be
   * 'manual'` tells the next reader nothing about WHICH of the footer, the
   * parser or the launch moved. The report names the mode launched, the rung
   * expected, what the parser actually returned (observed + source + raw), the
   * footer line actually on screen, and where to fix and re-record.
   */
  function report(
    args: string[],
    expected: string,
    fragment: string,
    scrape: FooterScrape,
    fixture: string,
  ): string {
    const version = info.detectedVersion || "?";
    const r = parsePermissionMode(scrape.text, "claude-code");
    const launch = args.length === 0 ? "(no permission flag)" : args.join(" ");
    return (
      `claude ${version} LIVE FOOTER DRIFT.\n` +
      `  launch flags:   ${launch}\n` +
      `  expected rung:  ${expected}\n` +
      `  expected text:  starts with "${fragment}"\n` +
      `  observed:       ${r ? `"${r.observed}"` : "(parsePermissionMode returned null)"}\n` +
      `  source:         ${r?.source ?? "n/a"}\n` +
      `  raw:            ${r?.raw === undefined ? "(none)" : `"${r.raw}"`}\n` +
      `  footer line:    ${glyphLine(scrape.text)}\n` +
      `  composer ready: ${scrape.ready ? "yes" : "NO (readyForInput never went true)"}\n` +
      `  session status: ${scrape.fatal === "" ? "healthy" : scrape.fatal}\n` +
      `  If the footer was RENAMED: update claudeFooterRungs / claudeModeFooterRE in ` +
      `${FOOTER_PARSER} and re-record ${fixture}.\n` +
      `  If the FLAG was renamed: update ${SYMBOLS} and checks 1-2 above.\n` +
      `  --- screen ---\n${scrape.text}\n  --- end screen ---`
    );
  }

  /**
   * assertRung is the shared BODY of the six tests — never a shared test().
   * Each caller below owns its own test(), so one failing mode cannot hide the
   * other five and no single test carries six cold launches.
   *
   * `expected === undefined` means "any known rung" (the flagless case).
   */
  async function assertRung(
    args: string[],
    fragment: string,
    expected: PermissionRung | undefined,
    fixture: string,
  ): Promise<void> {
    const version = info.detectedVersion || "?";
    const scrape = await launchAndScrape(info, args);
    const label = expected ?? "any known ladder rung";
    const rep = report(args, label, fragment, scrape, fixture);

    // A dead session is never a footer-drift finding — say what actually killed
    // it. The PTY captured claude's own stderr, so a rejected flag reports
    // `error: unexpected argument '--permission-mode' found` right here rather
    // than as "no footer after 240 s".
    expect(
      scrape.fatal,
      `claude ${version}: session died before the footer painted.\n${rep}`,
    ).toBe("");

    const reading = parsePermissionMode(scrape.text, "claude-code");
    if (reading === null) {
      // Thrown, not expect()ed, so the narrowing survives below —
      // parsePermissionMode returning null for "claude-code" means the claude
      // arm of the parser is GONE, which is drift in its own right.
      throw new Error(
        `claude ${version}: parsePermissionMode returned null for harness ` +
          `"claude-code" — the claude arm of ${FOOTER_PARSER} has been removed.\n${rep}`,
      );
    }

    // The reading must come from a live footer parse. `unparsed_footer` is the
    // precise signature of a RENAME (a glyph line is painted, its fragment did
    // not map to a rung); `no_footer` means nothing painted at all.
    expect(
      reading.source,
      `claude ${version}: expected the reading's source to be "footer" (a live footer ` +
        `parse), got "${reading.source}".\n${rep}`,
    ).toBe("footer");

    // THE LOAD-BEARING ASSERTION — the parser's output, never a test-local
    // regex over `fragment`.
    if (expected === undefined) {
      expect(
        CLAUDE_KNOWN_RUNGS,
        `claude ${version}: the FLAGLESS default footer did not parse to any known ladder ` +
          `rung. This is the footer EVERY caller on main hits today (no caller passes a ` +
          `permission flag), so its rename breaks detection for everybody.\n${rep}`,
      ).toContain(reading.observed);
    } else {
      expect(
        reading.observed,
        `claude ${version}: the footer no longer reads back the launched rung.\n${rep}`,
      ).toBe(expected);
    }
  }

  // ── The flagless default — the case that matters most ──────────────────────
  //
  // Every caller on main today passes no permission flag, so the harness DEFAULT
  // footer is the one whose rename breaks detection for everybody. It asserts
  // only that the footer parses to SOME known rung, deliberately NOT `manual`:
  // pinning the default is the brittle version of the same check, and claude has
  // already changed it once (to Manual). A future flip would then fail this test
  // for a reason that has nothing to do with the parser.
  test.skipIf(skip)(
    "claude-code: flagless launch — the DEFAULT footer parses to a known ladder rung",
    async () => {
      // A normalizer that collapsed or dropped rungs would silently widen (or
      // empty) the accepted set, turning the assertion below into a tautology.
      // Guard the derivation before relying on it.
      expect(
        CLAUDE_KNOWN_RUNGS,
        `claude: normalizePermissionRung no longer maps every claude launch spelling to a ` +
          `rung — got [${CLAUDE_KNOWN_RUNGS.map((r) => String(r)).join(", ")}] from ` +
          `[${CLAUDE_FOOTER_CASES.map((c) => c.mode).join(", ")}] (${FOOTER_PARSER}). The ` +
          `accepted set this test derives from cannot be formed.`,
      ).not.toContain(undefined);
      expect(new Set(CLAUDE_KNOWN_RUNGS).size).toBe(CLAUDE_FOOTER_CASES.length);

      await assertRung(
        [],
        CLAUDE_FOOTER_CASES.map((c) => c.fragment).join(" | "),
        undefined,
        `${FOOTER_CORPUS}<the default mode>`,
      );
    },
    TEST_TIMEOUT,
  );

  // ── The five named modes, one test() each ──────────────────────────────────
  for (const { mode, fragment } of CLAUDE_FOOTER_CASES) {
    const expected = normalizePermissionRung(mode, "claude-code");
    const args = [ClaudePermissionModeFlag, mode];
    const fixture = `${FOOTER_CORPUS}${mode === ClaudeModeAcceptEdits ? "accept-edits" : mode === ClaudeModeBypassPermissions ? "bypass" : mode}`;

    // `manual` gets its own test() for a reason beyond the per-mode rule: it is
    // the ONLY footer lacking the "(shift+tab to cycle)" suffix, so a
    // suffix-requiring regex regression in parsePermissionMode must fail loudly
    // here rather than be masked by a shared loop body.
    test.skipIf(skip)(
      `claude-code: \`${ClaudePermissionModeFlag} ${mode}\` — live footer parses as rung \`${expected ?? "?"}\``,
      async () => {
        expect(
          expected,
          `claude: normalizePermissionRung no longer maps the launch spelling "${mode}" to ` +
            `any ladder rung (${FOOTER_PARSER}) — the claude arm of the normalizer has lost ` +
            `the entry this test derives its expectation from.`,
        ).not.toBeUndefined();
        await assertRung(args, fragment, expected, fixture);
      },
      TEST_TIMEOUT,
    );
  }
});
